targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: supabase_playground|lib/graphql/schema.graphql
          global_enum_fallbacks: true
          type_overrides:
            Date:
              name: DateTime
            DateTime:
              name: DateTime
            JSON:
              name: JsonObject
              import: package:built_value/json_object.dart

      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: supabase_playground|lib/graphql/schema.graphql
          type_overrides:
            Date:
              name: DateTime
            DateTime:
              name: DateTime
            JSON:
              name: JsonObject
              import: package:built_value/json_object.dart
          custom_serializers:
            - name: DateTimeSerializer
              import: package:supabase_playground/graphql/serializer/date_time_serializer.dart
            - name: JsonObjectSerializer
              import: package:built_value/src/json_object_serializer.dart
      json_serializable:
        options:
          create_field_map: true
          create_per_field_to_json: true
