name: supabase_playground
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.5.2
  flutter_dotenv: ^5.1.0
  hooks_riverpod: ^3.0.0-dev.3
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^3.0.0-dev.3
  infinite_scroll_pagination: ^4.0.0
  ferry: ^0.16.0+1
  built_value: ^8.9.2
  gql_http_link: ^1.0.1+1
  http: ^1.2.1
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  riverpod_generator: ^3.0.0-dev.11
  build_runner: ^2.4.9
  custom_lint: ^0.5.11
  riverpod_lint: ^3.0.0-dev.4
  ferry_generator: ^0.10.0

flutter:
  uses-material-design: true
  assets:
    - .env
